/*
Task 1: Input and output without C code
Connect an LED to GP0 and two pushbuttons: One connected to GP1 and
one to GP2. This is the same setup as Task2 on the previous lab assignment.
This time, you are not allowed to use C functions to read from the input pin
or to turn the LED on/off! You have to use reads and writes to and from
hardware registers. You can use the example from the book, chapter 9. 
 */